# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'adpkd_tool_design.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDockWidget, QFrame, QHBoxLayout,
    QLabel, QLayout, QLineEdit, QListView,
    QListWidget, QListWidgetItem, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QSlider, QStatusBar,
    QTabWidget, QToolBar, QToolBox, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1573, 1010)
        icon = QIcon()
        icon.addFile(u"./icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(Qt.ToolButtonFollowStyle)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.actionOpenDirDialog = QAction(MainWindow)
        self.actionOpenDirDialog.setObjectName(u"actionOpenDirDialog")
        icon1 = QIcon()
        icon1.addFile(u"./icons/folder-open.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpenDirDialog.setIcon(icon1)
        self.actionOpenNextImg = QAction(MainWindow)
        self.actionOpenNextImg.setObjectName(u"actionOpenNextImg")
        icon2 = QIcon()
        icon2.addFile(u"./icons/arrow-forward-circle-outline.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpenNextImg.setIcon(icon2)
        self.actionOpenPrevImg = QAction(MainWindow)
        self.actionOpenPrevImg.setObjectName(u"actionOpenPrevImg")
        icon3 = QIcon()
        icon3.addFile(u"./icons/arrow-back-circle-outline.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpenPrevImg.setIcon(icon3)
        self.actionCreateMode = QAction(MainWindow)
        self.actionCreateMode.setObjectName(u"actionCreateMode")
        icon4 = QIcon()
        icon4.addFile(u"./icons/crop-sharp.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCreateMode.setIcon(icon4)
        self.actionCellDetectionDir = QAction(MainWindow)
        self.actionCellDetectionDir.setObjectName(u"actionCellDetectionDir")
        icon5 = QIcon()
        icon5.addFile(u"./icons/images.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCellDetectionDir.setIcon(icon5)
        self.actionCellDetection = QAction(MainWindow)
        self.actionCellDetection.setObjectName(u"actionCellDetection")
        icon6 = QIcon()
        icon6.addFile(u"./icons/image.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCellDetection.setIcon(icon6)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon7 = QIcon()
        icon7.addFile(u"./icons/save-sharp.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSave.setIcon(icon7)
        self.actionReload_Img = QAction(MainWindow)
        self.actionReload_Img.setObjectName(u"actionReload_Img")
        icon8 = QIcon()
        icon8.addFile(u"./icons/reload-outline.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionReload_Img.setIcon(icon8)
        self.actionSetEditMode = QAction(MainWindow)
        self.actionSetEditMode.setObjectName(u"actionSetEditMode")
        icon9 = QIcon()
        icon9.addFile(u"./icons/edit.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSetEditMode.setIcon(icon9)
        self.actionDeleteSelectedShape = QAction(MainWindow)
        self.actionDeleteSelectedShape.setObjectName(u"actionDeleteSelectedShape")
        icon10 = QIcon()
        icon10.addFile(u"./icons/cut.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDeleteSelectedShape.setIcon(icon10)
        self.actionGenOutput = QAction(MainWindow)
        self.actionGenOutput.setObjectName(u"actionGenOutput")
        icon11 = QIcon()
        icon11.addFile(u"./icons/bar-chart-sharp.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionGenOutput.setIcon(icon11)
        self.actionResetImg = QAction(MainWindow)
        self.actionResetImg.setObjectName(u"actionResetImg")
        icon12 = QIcon()
        icon12.addFile(u"./icons/trash-bin.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionResetImg.setIcon(icon12)
        self.actionResetAll = QAction(MainWindow)
        self.actionResetAll.setObjectName(u"actionResetAll")
        icon13 = QIcon()
        icon13.addFile(u"./icons/resetall.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionResetAll.setIcon(icon13)
        self.actionZoomIn = QAction(MainWindow)
        self.actionZoomIn.setObjectName(u"actionZoomIn")
        icon14 = QIcon()
        icon14.addFile(u"./icons/zoom-in.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionZoomIn.setIcon(icon14)
        self.actionZoomOut = QAction(MainWindow)
        self.actionZoomOut.setObjectName(u"actionZoomOut")
        icon15 = QIcon()
        icon15.addFile(u"./icons/zoom-out.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionZoomOut.setIcon(icon15)
        self.actionOriginalSize = QAction(MainWindow)
        self.actionOriginalSize.setObjectName(u"actionOriginalSize")
        icon16 = QIcon()
        icon16.addFile(u"./icons/undo.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOriginalSize.setIcon(icon16)
        self.actionFitWidth = QAction(MainWindow)
        self.actionFitWidth.setObjectName(u"actionFitWidth")
        icon17 = QIcon()
        icon17.addFile(u"./icons/fit-width.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionFitWidth.setIcon(icon17)
        self.actionFitWindow = QAction(MainWindow)
        self.actionFitWindow.setObjectName(u"actionFitWindow")
        self.actionOpenWeightsMask = QAction(MainWindow)
        self.actionOpenWeightsMask.setObjectName(u"actionOpenWeightsMask")
        icon18 = QIcon()
        icon18.addFile(u"./icons/file.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpenWeightsMask.setIcon(icon18)
        self.actionOpenWeightsMask.setIconVisibleInMenu(False)
        self.actionOpenWeightsUnet = QAction(MainWindow)
        self.actionOpenWeightsUnet.setObjectName(u"actionOpenWeightsUnet")
        self.actionOpenWeightsUnet.setIcon(icon18)
        self.actionContourmode = QAction(MainWindow)
        self.actionContourmode.setObjectName(u"actionContourmode")
        self.actionContourmode.setCheckable(True)
        icon19 = QIcon()
        icon19.addFile(u"./icons/scan.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionContourmode.setIcon(icon19)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMaximumSize(QSize(1300, 917))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QSize(40, 30))
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.dockWidget_2 = QDockWidget(MainWindow)
        self.dockWidget_2.setObjectName(u"dockWidget_2")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_2.sizePolicy().hasHeightForWidth())
        self.dockWidget_2.setSizePolicy(sizePolicy)
        self.dockWidget_2.setMinimumSize(QSize(240, 38))
        self.dockWidget_2.setMaximumSize(QSize(240, 1600))
        self.dockWidget_2.setAllowedAreas(Qt.RightDockWidgetArea)
        self.dockWidgetContents_3 = QWidget()
        self.dockWidgetContents_3.setObjectName(u"dockWidgetContents_3")
        self.toolBox = QToolBox(self.dockWidgetContents_3)
        self.toolBox.setObjectName(u"toolBox")
        self.toolBox.setGeometry(QRect(0, 0, 251, 341))
        self.page1 = QWidget()
        self.page1.setObjectName(u"page1")
        self.page1.setGeometry(QRect(0, 0, 251, 239))
        self.line_4 = QFrame(self.page1)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(-3, 0, 231, 20))
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_5 = QFrame(self.page1)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(0, 90, 231, 20))
        self.line_5.setFrameShape(QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.horizontalLayoutWidget = QWidget(self.page1)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(10, 110, 221, 41))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName(u"label_2")

        self.horizontalLayout.addWidget(self.label_2)

        self.scalingInput = QLineEdit(self.horizontalLayoutWidget)
        self.scalingInput.setObjectName(u"scalingInput")
        self.scalingInput.setMaxLength(10)
        self.scalingInput.setClearButtonEnabled(True)

        self.horizontalLayout.addWidget(self.scalingInput)

        self.verticalLayoutWidget = QWidget(self.page1)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 20, 221, 76))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(u"label")

        self.verticalLayout.addWidget(self.label)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.resolution_slider = QSlider(self.verticalLayoutWidget)
        self.resolution_slider.setObjectName(u"resolution_slider")
        self.resolution_slider.setMinimum(1)
        self.resolution_slider.setMaximum(5)
        self.resolution_slider.setOrientation(Qt.Horizontal)

        self.horizontalLayout_2.addWidget(self.resolution_slider)

        self.slider_value = QLabel(self.verticalLayoutWidget)
        self.slider_value.setObjectName(u"slider_value")

        self.horizontalLayout_2.addWidget(self.slider_value)


        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.toolBox.addItem(self.page1, u"Parameter")
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.page_2.setGeometry(QRect(0, 0, 251, 239))
        self.listWidget = QListWidget(self.page_2)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(0, 20, 231, 221))
        self.listWidget.setMovement(QListView.Free)
        self.listWidget.setProperty("isWrapping", False)
        self.line_3 = QFrame(self.page_2)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(-3, 0, 231, 20))
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.toolBox.addItem(self.page_2, u"File List")
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.page_3.setGeometry(QRect(0, 0, 251, 239))
        self.label_3 = QLabel(self.page_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 30, 101, 16))
        self.nn_path_label = QLabel(self.page_3)
        self.nn_path_label.setObjectName(u"nn_path_label")
        self.nn_path_label.setGeometry(QRect(10, 50, 241, 41))
        self.nn_path_label.setWordWrap(True)
        self.actionNN_Verzeichnis_2 = QPushButton(self.page_3)
        self.actionNN_Verzeichnis_2.setObjectName(u"actionNN_Verzeichnis_2")
        self.actionNN_Verzeichnis_2.setGeometry(QRect(120, 20, 113, 32))
        self.actionChangePenColor = QPushButton(self.page_3)
        self.actionChangePenColor.setObjectName(u"actionChangePenColor")
        self.actionChangePenColor.setGeometry(QRect(90, 100, 151, 32))
        self.actionChangePenWidth = QPushButton(self.page_3)
        self.actionChangePenWidth.setObjectName(u"actionChangePenWidth")
        self.actionChangePenWidth.setGeometry(QRect(90, 130, 151, 32))
        self.label_4 = QLabel(self.page_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 120, 81, 16))
        self.line = QFrame(self.page_3)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 0, 231, 16))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_2 = QFrame(self.page_3)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 90, 231, 16))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.toolBox.addItem(self.page_3, u"Settings")
        self.dockWidget_2.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.dockWidget_2)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1573, 22))
        MainWindow.setMenuBar(self.menubar)

        self.toolBar.addAction(self.actionOpenDirDialog)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOpenPrevImg)
        self.toolBar.addAction(self.actionOpenNextImg)
        self.toolBar.addAction(self.actionCreateMode)
        self.toolBar.addAction(self.actionDeleteSelectedShape)
        self.toolBar.addAction(self.actionCellDetection)
        self.toolBar.addAction(self.actionContourmode)
        self.toolBar.addAction(self.actionReload_Img)
        self.toolBar.addAction(self.actionCellDetectionDir)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionGenOutput)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionResetImg)
        self.toolBar.addAction(self.actionResetAll)

        self.retranslateUi(MainWindow)
        self.resolution_slider.valueChanged.connect(self.slider_value.setNum)

        self.toolBox.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"ADPKD Support Tool", None))
        self.actionOpenDirDialog.setText(QCoreApplication.translate("MainWindow", u"Open folder", None))
#if QT_CONFIG(tooltip)
        self.actionOpenDirDialog.setToolTip(QCoreApplication.translate("MainWindow", u"Open folder", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionOpenDirDialog.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpenNextImg.setText(QCoreApplication.translate("MainWindow", u"N\u00e4chstes Bild", None))
#if QT_CONFIG(tooltip)
        self.actionOpenNextImg.setToolTip(QCoreApplication.translate("MainWindow", u"Next Image", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionOpenNextImg.setShortcut(QCoreApplication.translate("MainWindow", u"D", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpenPrevImg.setText(QCoreApplication.translate("MainWindow", u"Vorheriges Bild", None))
        self.actionOpenPrevImg.setIconText(QCoreApplication.translate("MainWindow", u"Vorheriges Bild", None))
#if QT_CONFIG(tooltip)
        self.actionOpenPrevImg.setToolTip(QCoreApplication.translate("MainWindow", u"Previous Image", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionOpenPrevImg.setShortcut(QCoreApplication.translate("MainWindow", u"A", None))
#endif // QT_CONFIG(shortcut)
        self.actionCreateMode.setText(QCoreApplication.translate("MainWindow", u"Markierungen erstellen", None))
#if QT_CONFIG(tooltip)
        self.actionCreateMode.setToolTip(QCoreApplication.translate("MainWindow", u"Create BoundingBox", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionCreateMode.setShortcut(QCoreApplication.translate("MainWindow", u"W", None))
#endif // QT_CONFIG(shortcut)
        self.actionCellDetectionDir.setText(QCoreApplication.translate("MainWindow", u"Automatische Erkennung des Ordners", None))
#if QT_CONFIG(tooltip)
        self.actionCellDetectionDir.setToolTip(QCoreApplication.translate("MainWindow", u"Automatic Detection of folder", None))
#endif // QT_CONFIG(tooltip)
        self.actionCellDetection.setText(QCoreApplication.translate("MainWindow", u"Automatische Erkennung", None))
#if QT_CONFIG(tooltip)
        self.actionCellDetection.setToolTip(QCoreApplication.translate("MainWindow", u"Automatic detection of a single image", None))
#endif // QT_CONFIG(tooltip)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Speichern", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("MainWindow", u"Save", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionReload_Img.setText(QCoreApplication.translate("MainWindow", u"Bild neu laden", None))
#if QT_CONFIG(tooltip)
        self.actionReload_Img.setToolTip(QCoreApplication.translate("MainWindow", u"Reload current image", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionReload_Img.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionSetEditMode.setText(QCoreApplication.translate("MainWindow", u"Markierungen bearbeiten", None))
#if QT_CONFIG(tooltip)
        self.actionSetEditMode.setToolTip(QCoreApplication.translate("MainWindow", u"Edit BoundingBox ", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSetEditMode.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+J", None))
#endif // QT_CONFIG(shortcut)
        self.actionDeleteSelectedShape.setText(QCoreApplication.translate("MainWindow", u"Markierungen l\u00f6schen", None))
#if QT_CONFIG(tooltip)
        self.actionDeleteSelectedShape.setToolTip(QCoreApplication.translate("MainWindow", u"Delete BoundingBox", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionDeleteSelectedShape.setShortcut(QCoreApplication.translate("MainWindow", u"Del", None))
#endif // QT_CONFIG(shortcut)
        self.actionGenOutput.setText(QCoreApplication.translate("MainWindow", u"Ergebnis erzeugen", None))
#if QT_CONFIG(tooltip)
        self.actionGenOutput.setToolTip(QCoreApplication.translate("MainWindow", u"Generate result", None))
#endif // QT_CONFIG(tooltip)
        self.actionResetImg.setText(QCoreApplication.translate("MainWindow", u"Markierungen zur\u00fccksetzen", None))
#if QT_CONFIG(tooltip)
        self.actionResetImg.setToolTip(QCoreApplication.translate("MainWindow", u"Reset annotations", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionResetImg.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionResetAll.setText(QCoreApplication.translate("MainWindow", u"Zur\u00fccksetzen aller Einstellungen & Neu starten", None))
#if QT_CONFIG(tooltip)
        self.actionResetAll.setToolTip(QCoreApplication.translate("MainWindow", u"Reset settings & restart", None))
#endif // QT_CONFIG(tooltip)
        self.actionZoomIn.setText(QCoreApplication.translate("MainWindow", u"Zoom In", None))
#if QT_CONFIG(tooltip)
        self.actionZoomIn.setToolTip(QCoreApplication.translate("MainWindow", u"Zoom In", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionZoomIn.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl++", None))
#endif // QT_CONFIG(shortcut)
        self.actionZoomOut.setText(QCoreApplication.translate("MainWindow", u"Zoom out", None))
#if QT_CONFIG(tooltip)
        self.actionZoomOut.setToolTip(QCoreApplication.translate("MainWindow", u"Zoom out", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionZoomOut.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+-", None))
#endif // QT_CONFIG(shortcut)
        self.actionOriginalSize.setText(QCoreApplication.translate("MainWindow", u"Original Size", None))
#if QT_CONFIG(tooltip)
        self.actionOriginalSize.setToolTip(QCoreApplication.translate("MainWindow", u"Original Size", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionOriginalSize.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+0", None))
#endif // QT_CONFIG(shortcut)
        self.actionFitWidth.setText(QCoreApplication.translate("MainWindow", u"Fit Width", None))
#if QT_CONFIG(tooltip)
        self.actionFitWidth.setToolTip(QCoreApplication.translate("MainWindow", u"Fit Width", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionFitWidth.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionFitWindow.setText(QCoreApplication.translate("MainWindow", u"Fit Window", None))
#if QT_CONFIG(tooltip)
        self.actionFitWindow.setToolTip(QCoreApplication.translate("MainWindow", u"Zoom follows window size", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionFitWindow.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpenWeightsMask.setText(QCoreApplication.translate("MainWindow", u"openWeightsMask", None))
        self.actionOpenWeightsMask.setIconText(QCoreApplication.translate("MainWindow", u"openWeightsMask", None))
#if QT_CONFIG(tooltip)
        self.actionOpenWeightsMask.setToolTip(QCoreApplication.translate("MainWindow", u"Choose weights for Mask Detector", None))
#endif // QT_CONFIG(tooltip)
        self.actionOpenWeightsUnet.setText(QCoreApplication.translate("MainWindow", u"OpenWeightsUnet", None))
#if QT_CONFIG(tooltip)
        self.actionOpenWeightsUnet.setToolTip(QCoreApplication.translate("MainWindow", u"Choose weights for Segmentation Detector (U-Net)", None))
#endif // QT_CONFIG(tooltip)
        self.actionContourmode.setText(QCoreApplication.translate("MainWindow", u"Contourmode", None))
#if QT_CONFIG(tooltip)
        self.actionContourmode.setToolTip(QCoreApplication.translate("MainWindow", u"Contourmode", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionContourmode.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+C", None))
#endif // QT_CONFIG(shortcut)
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u00b5m scaling", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Resolution of contour points", None))
        self.slider_value.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page1), QCoreApplication.translate("MainWindow", u"Parameter", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QCoreApplication.translate("MainWindow", u"File List", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Model file path", None))
        self.nn_path_label.setText(QCoreApplication.translate("MainWindow", u"PATH LABEL", None))
        self.actionNN_Verzeichnis_2.setText(QCoreApplication.translate("MainWindow", u"Change path", None))
        self.actionChangePenColor.setText(QCoreApplication.translate("MainWindow", u"Brush colour", None))
        self.actionChangePenWidth.setText(QCoreApplication.translate("MainWindow", u"Brush width", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Manual draw", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QCoreApplication.translate("MainWindow", u"Settings", None))
    # retranslateUi

